RHTAPINST-81: Quay Integration
redhat-appstudio/tssc-cli pull request #102
Opened 2024-07-17 13:57 UTC by otaviof

Using a script to initialise Quay super user and create a docker-registry secret for the RHTAP integration.

2024-07-17 20:15 UTC, Roming22 requested changes
The generated secret does not seem to meet the requirements.

In my test I got:
```
kind: Secret
apiVersion: v1
metadata:
  name: rhtap-quay-integration
  namespace: rhtap
...
data:
  .dockerconfigjson: eyJ...9fQ==
type: kubernetes.io/dockerconfigjson
```

I'm expecting:
```
kind: Secret
apiVersion: v1
metadata:
  name: rhtap-quay-integration
  namespace: rhtap
...
data:
  dockerconfigjson: eyA...9fQ==
  token: YU...Tw==
  url: aH...lv
type: Opaque
```

2024-07-18 07:47 UTC, otaviof commented
> The generated secret does not seem to meet the requirements.
> 
> In my test I got:
> 
> ```
> kind: Secret
> apiVersion: v1
> metadata:
>   name: rhtap-quay-integration
>   namespace: rhtap
> ...
> data:
>   .dockerconfigjson: eyJ...9fQ==
> type: kubernetes.io/dockerconfigjson
> ```
> 
> I'm expecting:
> 
> ```
> kind: Secret
> apiVersion: v1
> metadata:
>   name: rhtap-quay-integration
>   namespace: rhtap
> ...
> data:
>   dockerconfigjson: eyA...9fQ==
>   token: YU...Tw==
>   url: aH...lv
> type: Opaque
> ```

Indeed, the secret was missing these two attributes, please consider the latest changes.

For practical reasons I've kept the secret type `docker-registry`, the `oc create secret` offers flags that perfectly matches the fields we need. Additionally it follows common Kubernetes convention.

2024-07-18 13:31 UTC, Roming22 commented
It looks like the quay-helper.sh script is not complete, as image builds are failing.

I've identified the following gaps:
1. a default org must be created (I propose `rhtap`o)
2. a robot user must be created in that org, with enough rights to create repos in the org, and push/pull in all repos in the org.
3. the integration secret must reference the robot account instead of the superuser.
4. the dockerconfigjson must reference the org in the url. Eg: `{"auths":{"rhtap-quay-quay-rhtap-quay.apps.rosa.ot6bb-ev9pr-ce3.72z3.p3.openshiftapps.com/rhtap": {"username":"admin","password":"Fgan92KTNiOcU7EJ","email":"admin@rhtap-quay-quay-rhtap-quay.apps.rosa.ot6bb-ev9pr-ce3.72z3.p3.openshiftapps.com","auth":"YWRtaW46RmdhbjkyS1ROaU9jVTdFSg=="}}}`

2024-07-23 16:34 UTC, Roming22 approved these changes

2024-07-23 16:34 UTC, merged