fix: Enable scannerV4 in ACS
redhat-appstudio/tssc-cli pull request #299
Opened 2024-11-05 14:44 UTC by Roming22

Recommended configuration after reaching out the ACS team regarding RHTAPBUGS-1316

2024-11-05 17:24 UTC, Roming22 commented
/retest

2024-11-07 13:22 UTC, xinredhat commented
/retest

2025-01-08 21:12 UTC, lcarva commented on installer/charts/rhtap-acs-scanner/scripts/test-acs-image-scan.sh
> +IMAGE="${IMAGE:-quay.io/fedora/fedora:36-x86_64@sha256:d6e4c7d6d1eaa24d71c8efd7432890acdc0179502224d0aaad6bb05d15ffde19}"
Oh?

2025-01-08 21:14 UTC, lcarva commented on installer/charts/rhtap-acs-scanner/scripts/test-acs-image-scan.sh
> +IMAGE="${IMAGE:-quay.io/fedora/fedora:36-x86_64@sha256:d6e4c7d6d1eaa24d71c8efd7432890acdc0179502224d0aaad6bb05d15ffde19}"
I understand it's only used for testing the installation, but can we use an image from registry.redhat.io instead?

2025-01-08 23:01 UTC, Roming22 commented on installer/charts/rhtap-acs-scanner/scripts/test-acs-image-scan.sh
> +IMAGE="${IMAGE:-quay.io/fedora/fedora:36-x86_64@sha256:d6e4c7d6d1eaa24d71c8efd7432890acdc0179502224d0aaad6bb05d15ffde19}"
Unfortunately that's more complicated than just switching the image, as ACS would need to be setup to be integrated with registry.redhat.io (it's basically currently returning an error saying it can't get the image from that registry).

I've chosen as close to possible to a "Red Hat" image by using a Fedora image hosted on quay, which are 2 products strongly linked to our brand. Let me know if you don't think that's good enough.

2025-01-09 10:38 UTC, otaviof requested changes

2025-01-09 10:38 UTC, otaviof commented on installer/charts/rhtap-acs-scanner/scripts/test-acs-image-scan.sh
> +ROX_API_TOKEN="$(kubectl get secrets -n rhtap rhtap-acs-integration -o jsonpath='{.data.token}' | base64 -d)"
You need to mount this secret on the testing POD, by doing so the `ROX_CENTRAL_ENDPOINT` and `ROX_API_TOKEN` will be available directly in the environment.

2025-01-09 10:38 UTC, otaviof commented on installer/charts/rhtap-acs-scanner/scripts/test-acs-image-scan.sh
> +echo
Please use a `emptyDir: {}` mount, so at the end of the container execution all data in the mount point will be gone.

2025-01-09 10:38 UTC, otaviof commented on installer/charts/rhtap-acs-scanner/templates/service-account.yaml
> +apiVersion: rbac.authorization.k8s.io/v1
Does it need "write" permission to Secrets?

2025-01-09 10:38 UTC, otaviof commented on installer/charts/rhtap-acs/templates/tests/test.yaml
> +        # Downloading the vulnerability DB can take a long time
By default we allow a 15 minute timeout. Should we make sure the Helm Chart installation waits longer than that?

2025-01-09 10:38 UTC, otaviof commented on installer/charts/rhtap-acs-scanner/scripts/test-acs-image-scan.sh
This script should live on the `installer/scritps` directory, with a symbolic link into the Helm Chart directory, following the approach taken by all other scripts. Please move it.

2025-01-09 14:08 UTC, lcarva commented on installer/charts/rhtap-acs-scanner/scripts/test-acs-image-scan.sh
> +IMAGE="${IMAGE:-quay.io/fedora/fedora:36-x86_64@sha256:d6e4c7d6d1eaa24d71c8efd7432890acdc0179502224d0aaad6bb05d15ffde19}"
Thanks for looking into it! I think it's fine because:

1. The contents of the fedora image are never executed.
2. The image comes from a registry that is managed by Red Hat.

2025-01-09 15:36 UTC, Roming22 commented on installer/charts/rhtap-acs-scanner/scripts/test-acs-image-scan.sh
> +ROX_API_TOKEN="$(kubectl get secrets -n rhtap rhtap-acs-integration -o jsonpath='{.data.token}' | base64 -d)"
Fixed

2025-01-09 15:36 UTC, Roming22 commented on installer/charts/rhtap-acs-scanner/scripts/test-acs-image-scan.sh
> +echo
Fixed

2025-01-09 15:37 UTC, Roming22 commented on installer/charts/rhtap-acs-scanner/templates/service-account.yaml
> +apiVersion: rbac.authorization.k8s.io/v1
In fact, we don't need the SA at all.
I now use the `default` SA in the `rhtap` namespace.

2025-01-09 15:38 UTC, Roming22 commented on installer/charts/rhtap-acs-scanner/scripts/test-acs-image-scan.sh
Fixed

2025-01-09 16:07 UTC, Roming22 commented on installer/charts/rhtap-acs/templates/tests/test.yaml
> +        # Downloading the vulnerability DB can take a long time
My tests shows that 15m is enough for the test to pass, we should be OK.

2025-01-09 16:42 UTC, Roming22 commented on installer/charts/rhtap-acs/templates/tests/test.yaml
> +        # Downloading the vulnerability DB can take a long time
Another test shows that the 15m Helm timeout does not apply to tests. I'm surprised by that result. There is a timeout flag (https://helm.sh/docs/helm/helm_test/#options), I wonder if we use it at all.

2025-01-09 16:43 UTC, Roming22 commented
/retest

2025-01-10 15:10 UTC, otaviof approved these changes
/lgtm

2025-01-10 15:48 UTC, merged