RHTAPINST-74: README.md
redhat-appstudio/tssc-cli pull request #86
Opened 2024-07-10 09:23 UTC by otaviof

Initial project documentation front page.

2024-07-10 10:51 UTC, prietyc123 commented
@otaviof the detailed process of using this cli would be handled via main documentation, correct?

2024-07-10 10:56 UTC, prietyc123 requested changes
Can we also add a quick demo section just to let contributor understand how they should start with this?

2024-07-10 14:30 UTC, otaviof commented
> @otaviof the detailed process of using this cli would be handled via main documentation, correct?

I'd like to tackle this after we rename a couple of internal subcommands, should happen quite soon, please.

2024-07-10 14:36 UTC, Roming22 commented on README.md
> +Red Hat Trusted Application Pipeline Instaler (`rhtap-cli`)
Instaler -> Installer

2024-07-10 15:00 UTC, otaviof commented on README.md
> +Red Hat Trusted Application Pipeline Instaler (`rhtap-cli`)
Thanks!

2024-07-10 15:01 UTC, otaviof commented
> Can we also add a quick demo section just to let contributor understand how they should start with this?

Please consider the latest changes, I've added the `CONTRIBUTING.md`.

2024-07-10 21:08 UTC, Roming22 commented on CONTRIBUTING.md
> +All the automation needed for the project lives in the [Makefile](Makefile). This file is the entry point for all the automation task in the project for CI, development and release
*tasks

2024-07-10 21:08 UTC, Roming22 commented on CONTRIBUTING.md
> +After you have cloned the repository and installed the requirements, you can start building. For that purpose you can simply run `make`, the default target builds the application on the `bin` directo
*in the `bin`

2024-07-10 21:09 UTC, Roming22 commented
Feel free to merge once the typos are fixed.

2024-07-11 02:20 UTC, otaviof commented on CONTRIBUTING.md
> +All the automation needed for the project lives in the [Makefile](Makefile). This file is the entry point for all the automation task in the project for CI, development and release
Thanks!

2024-07-11 02:20 UTC, otaviof commented on CONTRIBUTING.md
> +After you have cloned the repository and installed the requirements, you can start building. For that purpose you can simply run `make`, the default target builds the application on the `bin` directo
THanks!

2024-07-11 04:08 UTC, merged